name: command_palette
description: Flutter implementation of the Command Palette. Can be brought up via a keyboard shortcut.
version: 0.4.0
homepage: https://github.com/TNorbury/command_palette
issue_tracker: https://github.com/TNorbury/command_palette/issues
repository: https://github.com/TNorbury/command_palette
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  substring_highlight: ^1.0.33
  woozy_search: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

