name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
      with:
        environment: pub.dev
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true

